### ISSUE TITLE
Additional styling features - overview

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#287]
The following list gives an overview of styling features that are possible with SLD and openlayers, but not yet possible in geostyler. Existing issues regarding the respective styling feature were linked where applicable.

#### GENERAL

- [x] Complex symbols within one rule [#248](https://github.com/terrestris/geostyler/issues/248)
- [x] Multiple filters within one rule [#69](https://github.com/terrestris/geostyler/issues/69)

#### POINTS

- [x] Support various well known symbols [#241](https://github.com/terrestris/geostyler/issues/241)
- [x] Allow symbol rotation
- [x] Allow fonts being used as symbols [#243](https://github.com/terrestris/geostyler/issues/243)
- [x] Allow setting offsetXY for symbols (useful when creating complex symbols) [#96](https://github.com/geostyler/geostyler-style/pull/96)

#### LINES

- [x] Line offset (perpendicular offset)*
- [x] Graphics and well known symbols in lines [#242](https://github.com/terrestris/geostyler/issues/242)*
- [x] Describing style at intersections (linejoin parameter)
- [x] Describing style at end of lines (linecap parameter)

#### POLYGONS

- [x] Graphic Fill incl. pattern description with external graphics [#214](https://github.com/terrestris/geostyler/issues/214)*
- [x] Graphic Fill incl. pattern description with well known symbols [#214](https://github.com/terrestris/geostyler/issues/214)*
- [ ] Color gradient based on transformation function

#### LABELS

- [x] Label rotation
- [x] Label halo
- [ ] Label priorities for conflict resolution

#### FILTERS

- [ ] Toggle case-sensitivity for string operations
- [ ] Spatial operators, e.g. intersects, equals, etc.
- [ ] Filter expressions, e.g. transformation function (needed for classification of continuous values)

\* not natively supported by openlayers api (--> not implemented in geostyler-openlayers-parser)
